/** Major cities & towns across Andhra Pradesh for shop onboarding. */
export const ANDHRA_PRADESH_CITIES = [
  'Adoni',
  'Amaravati',
  'Anakapalle',
  'Anantapur',
  'Bapatla',
  'Bhimavaram',
  'Chilakaluripet',
  'Chirala',
  'Chittoor',
  'Dharmavaram',
  'Eluru',
  'Gudivada',
  'Guntakal',
  'Guntur',
  'Hindupur',
  'Kadapa',
  'Kakinada',
  'Kavali',
  'Kurnool',
  'Machilipatnam',
  'Madanapalle',
  'Markapur',
  'Nandyal',
  'Narasaraopet',
  'Nellore',
  'Ongole',
  'Palakollu',
  'Proddatur',
  'Rajahmundry',
  'Rayachoti',
  'Srikakulam',
  'Tadepalligudem',
  'Tadipatri',
  'Tanuku',
  'Tenali',
  'Tirupati',
  'Vijayawada',
  'Visakhapatnam',
  'Vizianagaram',
] as const;

export type ApCity = (typeof ANDHRA_PRADESH_CITIES)[number];

export const DEFAULT_AP_CITY: ApCity = 'Rajahmundry';
